/*

ALTER DATABASE CURRENT
SET COMPATIBILITY_LEVEL = 130; --SQL 2016

Options:
SET COMPATIBILITY_LEVEL = { 150 | 140 | 130 | 120 | 110 | 100 | 90 }  
*/


/*
SELECT name, compatibility_level FROM sys.databases;  

ALTER DATABASE AutoScaleCMRS
SET COMPATIBILITY_LEVEL = 130;

ALTER DATABASE AutoScaleCMRSAudit
SET COMPATIBILITY_LEVEL = 130;

ALTER DATABASE AutoScaleRTT
SET COMPATIBILITY_LEVEL = 130;

ALTER DATABASE RWBackOffice
SET COMPATIBILITY_LEVEL = 130;

ALTER DATABASE WebRW
SET COMPATIBILITY_LEVEL = 130;

ALTER DATABASE WM_Addresses_PRD
SET COMPATIBILITY_LEVEL = 130;

ALTER DATABASE WM_Dumpster_Permitting_PRD
SET COMPATIBILITY_LEVEL = 130;

ALTER DATABASE WM_Routing_PRD
SET COMPATIBILITY_LEVEL = 130;
*/
